[clipper.cpp] fix MS Visual Studio 2008 error C2668: 'abs': ambiguous call to overloaded function with
MS Visual Studio 2008 doesn't have std::abs(long long).
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=818391